export enum EffectType {
  Transfer = 1,
  GiveCredit,
  WinCredit,
  SpendCredit,
  Conditional,
  WinZenithium,
  GiveZenithium,
  Exile,
  WinInfluence,
  GiveInfluence,
  ResetInfluence,
  DevelopTechnology,
  GiveLeaderBadge,
  TakeLeaderBadge,
  Discard,
  Mobilize,
  Choice,
  TakeBonus,
  StealCredit,
  SpendZenithium,
  TakeTechnologyBonusToken,
  ShareCard
}
