export enum RuleId {
  Muligan = 1,
  PlayCard,
  DiscardAction,
  Transfer,
  GiveCredit,
  WinCredit,
  SpendCredit,
  Conditional,
  WinZenithium,
  GiveZenithium,
  Exile,
  WinInfluence,
  GiveInfluence,
  ResetInfluence,
  DevelopTechnology,
  GiveLeaderBadge,
  TakeLeaderBadge,
  Discard,
  Mobilize,
  Choice,
  TakeBonus,
  Refill,
  StealCredit
}
