export enum LocationType {
  PlanetBoardPlace = 1,
  TechnologyBoardPlace,
  DiplomacyBoardPlace,
  PlanetBoardInfluenceDiscSpace,
  TechnologyBoardTokenSpace,
  AgentDeck,
  PlayerHand,
  AgentDiscard,
  DiplomacyBoardLeaderBadgeSpace,
  Influence,
  TeamCredit,
  TeamZenithium,
  TeamLeaderBadge,
  BonusTokenStock,
  PlayerBonus,
  PlanetBoardBonusSpace,
  TechnologyBoardBonusSpace,
  TeamPlanets
}
